import 'package:decimal/decimal.dart';
import 'package:dio/dio.dart';
import 'package:fpdart/fpdart.dart';

import '../../../core/auth/session_manager.dart';
import '../../../core/models/app_exception.dart';
import '../../auth/data/auth_repository.dart' show DioProvider;
import 'models/oco_order_result.dart';
import 'models/order_enums.dart';
import 'models/spot_order.dart';

/// Data access for spot trading: place, cancel, query orders.
///
/// Every method returns `TaskEither<AppException, T>`. Repositories
/// never throw — failures are values.
abstract class SpotTradeRepository {
  /// `POST /api/v3/order` — place a new spot order.
  ///
  /// [clientOrderId] is generated by the caller so EC-9 reconciliation
  /// can match on it if the response is lost.
  TaskEither<AppException, SpotOrder> placeOrder({
    required String symbol,
    required OrderSide side,
    required OrderType type,
    required Decimal quantity,
    required String clientOrderId,
    Decimal? price,
    Decimal? stopPrice,
    TimeInForce? timeInForce,
  });

  /// `POST /api/v3/order/oco` — place a one-cancels-the-other pair.
  TaskEither<AppException, OcoOrderResult> placeOco({
    required String symbol,
    required OrderSide side,
    required Decimal quantity,
    required Decimal price,
    required Decimal stopPrice,
    required Decimal stopLimitPrice,
    required String listClientOrderId,
    TimeInForce stopLimitTimeInForce = TimeInForce.GTC,
  });

  /// `DELETE /api/v3/order` — cancel a single order by orderId.
  TaskEither<AppException, SpotOrder> cancelOrder({
    required String symbol,
    required int orderId,
  });

  /// `DELETE /api/v3/openOrders` — cancel all open orders for a symbol.
  TaskEither<AppException, List<SpotOrder>> cancelAllOrders({
    required String symbol,
  });

  /// `GET /api/v3/openOrders` — all open orders, optionally filtered
  /// by symbol.
  TaskEither<AppException, List<SpotOrder>> getOpenOrders({String? symbol});

  /// `GET /api/v3/order` — query a single order. Used for EC-9
  /// reconciliation when a place response is lost.
  TaskEither<AppException, SpotOrder> queryOrder({
    required String symbol,
    String? clientOrderId,
    int? orderId,
  });
}

class BinanceSpotTradeRepository implements SpotTradeRepository {
  BinanceSpotTradeRepository({
    required DioProvider spotDio,
    SessionManager? sessionManager,
  }) : _spot = spotDio,
       _sessionManager = sessionManager;

  final DioProvider _spot;
  final SessionManager? _sessionManager;

  // -------------------------------------------------------------------
  // Place order
  // -------------------------------------------------------------------

  @override
  TaskEither<AppException, SpotOrder> placeOrder({
    required String symbol,
    required OrderSide side,
    required OrderType type,
    required Decimal quantity,
    required String clientOrderId,
    Decimal? price,
    Decimal? stopPrice,
    TimeInForce? timeInForce,
  }) {
    final cancelToken = CancelToken();
    _sessionManager?.registerCancelToken(cancelToken);

    return TaskEither<AppException, SpotOrder>.tryCatch(() async {
      final params = <String, dynamic>{
        'symbol': symbol,
        'side': side.name,
        'type': type.name,
        'quantity': quantity.toString(),
        'newClientOrderId': clientOrderId,
        'newOrderRespType': 'FULL',
      };
      if (price != null) params['price'] = price.toString();
      if (stopPrice != null) params['stopPrice'] = stopPrice.toString();
      if (timeInForce != null) params['timeInForce'] = timeInForce.name;

      final response = await _spot().post<Map<String, dynamic>>(
        '/api/v3/order',
        queryParameters: params,
        cancelToken: cancelToken,
      );
      return SpotOrder.fromJson(response.data!);
    }, _toAppException).bimap(_cleanup(cancelToken), _cleanup(cancelToken));
  }

  // -------------------------------------------------------------------
  // Place OCO
  // -------------------------------------------------------------------

  @override
  TaskEither<AppException, OcoOrderResult> placeOco({
    required String symbol,
    required OrderSide side,
    required Decimal quantity,
    required Decimal price,
    required Decimal stopPrice,
    required Decimal stopLimitPrice,
    required String listClientOrderId,
    TimeInForce stopLimitTimeInForce = TimeInForce.GTC,
  }) {
    final cancelToken = CancelToken();
    _sessionManager?.registerCancelToken(cancelToken);

    return TaskEither<AppException, OcoOrderResult>.tryCatch(() async {
      final params = <String, dynamic>{
        'symbol': symbol,
        'side': side.name,
        'quantity': quantity.toString(),
        'price': price.toString(),
        'stopPrice': stopPrice.toString(),
        'stopLimitPrice': stopLimitPrice.toString(),
        'stopLimitTimeInForce': stopLimitTimeInForce.name,
        'listClientOrderId': listClientOrderId,
        'newOrderRespType': 'FULL',
      };

      final response = await _spot().post<Map<String, dynamic>>(
        '/api/v3/order/oco',
        queryParameters: params,
        cancelToken: cancelToken,
      );
      return OcoOrderResult.fromJson(response.data!);
    }, _toAppException).bimap(_cleanup(cancelToken), _cleanup(cancelToken));
  }

  // -------------------------------------------------------------------
  // Cancel
  // -------------------------------------------------------------------

  @override
  TaskEither<AppException, SpotOrder> cancelOrder({
    required String symbol,
    required int orderId,
  }) {
    final cancelToken = CancelToken();
    _sessionManager?.registerCancelToken(cancelToken);

    return TaskEither<AppException, SpotOrder>.tryCatch(() async {
      final response = await _spot().delete<Map<String, dynamic>>(
        '/api/v3/order',
        queryParameters: <String, dynamic>{
          'symbol': symbol,
          'orderId': orderId,
        },
        cancelToken: cancelToken,
      );
      return SpotOrder.fromJson(response.data!);
    }, _toAppException).bimap(_cleanup(cancelToken), _cleanup(cancelToken));
  }

  @override
  TaskEither<AppException, List<SpotOrder>> cancelAllOrders({
    required String symbol,
  }) {
    final cancelToken = CancelToken();
    _sessionManager?.registerCancelToken(cancelToken);

    return TaskEither<AppException, List<SpotOrder>>.tryCatch(() async {
      final response = await _spot().delete<List<dynamic>>(
        '/api/v3/openOrders',
        queryParameters: <String, dynamic>{'symbol': symbol},
        cancelToken: cancelToken,
      );
      return (response.data ?? const [])
          .whereType<Map<String, dynamic>>()
          .map(SpotOrder.fromJson)
          .toList(growable: false);
    }, _toAppException).bimap(_cleanup(cancelToken), _cleanup(cancelToken));
  }

  // -------------------------------------------------------------------
  // Query
  // -------------------------------------------------------------------

  @override
  TaskEither<AppException, List<SpotOrder>> getOpenOrders({String? symbol}) {
    final cancelToken = CancelToken();
    _sessionManager?.registerCancelToken(cancelToken);

    return TaskEither<AppException, List<SpotOrder>>.tryCatch(() async {
      final params = <String, dynamic>{};
      if (symbol != null) params['symbol'] = symbol;

      final response = await _spot().get<List<dynamic>>(
        '/api/v3/openOrders',
        queryParameters: params,
        cancelToken: cancelToken,
      );
      return (response.data ?? const [])
          .whereType<Map<String, dynamic>>()
          .map(SpotOrder.fromJson)
          .toList(growable: false);
    }, _toAppException).bimap(_cleanup(cancelToken), _cleanup(cancelToken));
  }

  @override
  TaskEither<AppException, SpotOrder> queryOrder({
    required String symbol,
    String? clientOrderId,
    int? orderId,
  }) {
    final cancelToken = CancelToken();
    _sessionManager?.registerCancelToken(cancelToken);

    return TaskEither<AppException, SpotOrder>.tryCatch(() async {
      final params = <String, dynamic>{'symbol': symbol};
      if (orderId != null) params['orderId'] = orderId;
      if (clientOrderId != null) {
        params['origClientOrderId'] = clientOrderId;
      }

      final response = await _spot().get<Map<String, dynamic>>(
        '/api/v3/order',
        queryParameters: params,
        cancelToken: cancelToken,
      );
      return SpotOrder.fromJson(response.data!);
    }, _toAppException).bimap(_cleanup(cancelToken), _cleanup(cancelToken));
  }

  // -------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------

  T Function(T) _cleanup<T>(CancelToken token) {
    return (value) {
      _sessionManager?.unregisterCancelToken(token);
      return value;
    };
  }

  AppException _toAppException(Object err, StackTrace _) {
    if (err is AppException) return err;
    if (err is DioException && err.error is AppException) {
      return err.error! as AppException;
    }
    return AppException.unknown(message: err.toString());
  }
}
